Fixed the dir name
microsoft/AdaptiveCards pull request #7583
Opened 2022-06-29 00:42 UTC by jwoo-msft

# Description

Corrected `Test` to `Tests`

2022-06-29 22:52 UTC, almedina-ms approved these changes

2022-07-06 19:39 UTC, beervoley requested changes
You'll need to adjust all the imports/usages of these files since their path has changed :)

2022-07-18 19:16 UTC, paulcam206 approved these changes

2022-07-18 19:16 UTC, paulcam206 commented
(just need to fix up usage/tests)

2022-08-24 18:00 UTC, licanhua approved these changes

2022-09-16 00:08 UTC, beervoley approved these changes

2022-09-16 00:08 UTC, merged