updated css
microsoft/AdaptiveCards pull request #7806
Opened 2022-08-31 22:12 UTC by jwoo-msft

# Related Issue
Fixed #7659 

# Description
Carousel pagenations become blended to background in high contrast mode. 
it addresses issue by using @media and removing the high contrast changes and sets appropriate background color for pagenation.

# How Verified
Manually verified as below.

### Before Fix
Berlin dark
![Screenshot 2022-08-31 145910-dark](https://user-images.githubusercontent.com/4112696/187794382-02f5c9bf-7b6d-4964-9f1f-4864ac07542c.png)

Berlin light
![Screenshot 2022-08-31 145938-light](https://user-images.githubusercontent.com/4112696/187794394-39c5f4a2-cc29-4b52-9626-55ccdcaba27c.png)

### After Fix
![Screenshot 2022-08-31 145303](https://user-images.githubusercontent.com/4112696/187794410-5ad4bc2b-d67a-42d0-8936-c529a9007ca4.png)

![Screenshot 2022-08-31 145327](https://user-images.githubusercontent.com/4112696/187794417-54507824-1b08-4c9d-83d2-f8f7d2c62df0.png)

2022-09-01 19:01 UTC, paulcam206 commented on source/nodejs/adaptivecards-designer/src/containers/berlin/berlin-container-dark.css
> +    .swiper-pagination-bullet {
system colors _should_ work. if not, I think that's more of a bug in either the browser or the OS :)

2022-09-01 19:11 UTC, paulcam206 requested changes

2022-09-01 19:11 UTC, paulcam206 commented on source/nodejs/adaptivecards-designer/src/containers/berlin/berlin-container-dark.css
> +@media(forced-colors: active) {
I think you also need to update the carousel CSS here:

https://github.com/microsoft/AdaptiveCards/blob/1be91e6612787a3dd6d78d7095d0c9f122fe7c52/source/nodejs/adaptivecards/src/scss/adaptivecards-carousel.scss#L8-L13

2022-09-02 00:10 UTC, jwoo-msft commented on source/nodejs/adaptivecards-designer/src/containers/berlin/berlin-container-dark.css
> +    .swiper-pagination-bullet {
thanks

2022-09-02 19:39 UTC, paulcam206 approved these changes

2022-09-02 19:39 UTC, merged